- src/collective/collectionfilter/tiles/configure.zcml
@petschki this should fix #16 - please check it out and merge if it works.
> Include plone.tiles zcml meta config. Fixes: #16

- CHANGES.rst
- setup.py
- src/collective/collectionfilter/interfaces.py
- src/collective/collectionfilter/profiles/default/metadata.xml
- src/collective/collectionfilter/profiles/default/registry.xml
- src/collective/collectionfilter/upgrades.zcml
- src/collective/collectionfilter/utils.py
> constrain selectable type of "Target Collection"

- CHANGES.rst
- src/collective/collectionfilter/filteritems.py
- src/collective/collectionfilter/tests/test_filteritems.py
- src/collective/collectionfilter/utils.py
> Fix for non-iterable catalog metadata in Python 3

- CHANGES.rst
- src/collective/collectionfilter/utils.py
> fix safe_iterable with None value

- CHANGES.rst
- src/collective/collectionfilter/filteritems.py
- src/collective/collectionfilter/utils.py
Fixes issue #42 for the 2.x branch
> Updated filteritems to properly narrow results and keep "all" count (from pigeonflight/issue-42 branch)

- CHANGES.rst
- src/collective/collectionfilter/contentfilter.py
- src/collective/collectionfilter/filteritems.py
- src/collective/collectionfilter/portlets/configure.zcml
- src/collective/collectionfilter/query.py
- src/collective/collectionfilter/testing.py
- src/collective/collectionfilter/tests/robot/keywords.robot
- src/collective/collectionfilter/tests/robot/test_filterportlets.robot
- src/collective/collectionfilter/tests/test_filteritems.py
- src/collective/collectionfilter/tests/test_maps.py
- src/collective/collectionfilter/vocabularies.py
and Tests for "and" filter type
and also fix a unicode bug with utf/unicode in the batch urls
> fix broken tests where 5.2 not longer accepts queries with operators no supported by index type 

- src/collective/collectionfilter/tests/robot/keywords.robot
- src/collective/collectionfilter/tests/robot/test_filtertiles.robot
Closes #71.
This PR will add robot tests for the mosaic tiles, testing the same features as the robot tests for the portlets.
> Robot tests for mosaic tiles

- src/collective/collectionfilter/baseviews.py
- src/collective/collectionfilter/tests/robot/keywords.robot
- src/collective/collectionfilter/tests/robot/test_filterportlets.robot
> Fix duplicate filters when displaying multiple filters on a single page

- CHANGES.rst
- src/collective/collectionfilter/filteritems.py
- src/collective/collectionfilter/vocabularies.py
> fix translating filter_values

- CHANGES.rst
- src/collective/collectionfilter/vocabularies.py
- test-5.0.x.cfg
> Added translation display_modifier for portal_type and Type.

- CHANGES.rst
- src/collective/collectionfilter/query.py
- src/collective/collectionfilter/tests/test_filteritems.py
> Fix filter_type for indexes without operator capabilities

- CHANGES.rst
- src/collective/collectionfilter/vocabularies.py
> refactored translate_portal_type; fixes #issue_108

- CHANGES.rst
- src/collective/collectionfilter/tiles/__init__.py
- src/collective/collectionfilter/tiles/filter.py
- src/collective/collectionfilter/tiles/maps.py
- src/collective/collectionfilter/tiles/search.py
- src/collective/collectionfilter/tiles/sorting.py
> Do not render tiles when page gets AJAX loaded

- CHANGES.rst
- src/collective/collectionfilter/baseviews.py
- src/collective/collectionfilter/portlets/collectionsearch.pt
- src/collective/collectionfilter/tiles/search.pt
> Do not add hidden field multiple times

- .gitignore
- README.rst
- src/collective/collectionfilter/baseviews.py
- src/collective/collectionfilter/filteritems.py
- src/collective/collectionfilter/portlets/collectionsearch.pt
- src/collective/collectionfilter/tests/robot/keywords.robot
- src/collective/collectionfilter/tests/robot/test_filterportlets.robot
- src/collective/collectionfilter/tests/robot/test_filterportlets_ajaxdisabled.robot
- src/collective/collectionfilter/tests/robot/test_sortingportlets.robot
- src/collective/collectionfilter/tests/test_robot.py
and bug which prevented any robot tests running for 5.0
and a bug that broke the filter portlet when sorting on python 2.7
> bug where searching without ajax and using multi filter fails

- CHANGES.rst
- README.rst
- src/collective/collectionfilter/filteritems.py
- src/collective/collectionfilter/vocabularies.py
Makes things like this possible: https://github.com/collective/collective.taxonomy/pull/107
> Add idx parameter to display_modifier call

- .github/workflows/main.yml
- CHANGES.rst
- base.cfg
- src/collective/collectionfilter/baseviews.py
- src/collective/collectionfilter/filteritems.py
- src/collective/collectionfilter/interfaces.py
- src/collective/collectionfilter/testing.py
- src/collective/collectionfilter/tests/test_robot.py
- src/collective/collectionfilter/tiles/__init__.py
- src/collective/collectionfilter/tiles/filter.py
- src/collective/collectionfilter/tiles/maps.py
- src/collective/collectionfilter/tiles/search.py
- src/collective/collectionfilter/tiles/sorting.py
- src/collective/collectionfilter/utils.py
- src/collective/collectionfilter/validator.py
- test-5.2.x.cfg
Applied, black, isort and added a black check step to GH actions CI.
Remark: coverage was broken and still is, otherwise all is fine.
> Enforce code style black 

- CHANGES.rst
- src/collective/collectionfilter/vocabularies.py
More robust behavior if data is not bogus.
> Fix sortkey function to not break if the title is not a string

- src/collective/__init__.py
- src/collective/collectionfilter/__init__.py
- src/collective/collectionfilter/baseviews.py
- src/collective/collectionfilter/interfaces.py
cleanup some obsolete Plone < 5.2 checks
> Cleanup Code

- CHANGES.rst
- src/collective/collectionfilter/baseviews.py
- src/collective/collectionfilter/utils.py
In a listing tile this may look like so: can look like `http://localhost:8080/Plone/de/veranstaltungen?collectionfilter=1&f29112d4f79a4bd0be3850d96148c8a3-b_start:int=80`
> fix batching in tiles, remove also pre/postfixed b_start and similar.

- .github/workflows/main.yml
- news/150.bugfix
- src/collective/collectionfilter/tests/robot/keywords.robot
- src/collective/collectionfilter/tests/robot/test_debug.robot
- src/collective/collectionfilter/tests/robot/test_tilesonly.robot
- src/collective/collectionfilter/tests/test_robot.py
- src/collective/collectionfilter/tiles/__init__.py
continued from #170 
fixes #150
> Fix for issue #150

- CHANGES.rst
- news/detranslation.bugfix
- news/reset-button.feature
- src/collective/collectionfilter/baseviews.py
- src/collective/collectionfilter/interfaces.py
- src/collective/collectionfilter/locales/de/LC_MESSAGES/collective.collectionfilter.po
- src/collective/collectionfilter/portlets/configure.zcml
- src/collective/collectionfilter/portlets/profiles/default/portlets.xml
- src/collective/collectionfilter/portlets/reset.pt
- src/collective/collectionfilter/portlets/reset.py
- src/collective/collectionfilter/tiles/configure.zcml
- src/collective/collectionfilter/tiles/profiles/default/registry.xml
- src/collective/collectionfilter/tiles/reset.pt
- src/collective/collectionfilter/tiles/reset.py
Replaces #182, work by @toalba on https://github.com/collective/collective.collectionfilter/tree/toalba-reset-button branch for 4.1 manually cherry picked and extended by @jensens for main.
> Add a Reset Button to Reset all Filters.
